# Generated by Django 5.1 on 2025-04-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_page_meta_title_alter_page_meta_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.CharField(
                blank=True,
                help_text="Can include slashes for nested routes (e.g., 'about-us/team')",
                max_length=255,
                unique=True,
            ),
        ),
    ]
