# Generated by Django 5.1 on 2025-04-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0028_activity_slider"),
        ("home", "0013_newslettersubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="featuredtour",
            name="slider_tours",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"slider": True},
                related_name="slider_tours",
                to="activity.activity",
            ),
        ),
    ]
