# Generated by Django 5.1 on 2025-04-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0028_activity_slider"),
        ("home", "0014_featuredtour_slider_tours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuredtour",
            name="slider_tours",
            field=models.ManyToManyField(
                blank=True, related_name="slider_tours", to="activity.activity"
            ),
        ),
    ]
