# Generated by Django 5.1 on 2025-01-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0021_activity_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='accommodation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='country',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='activity',
            name='group_size',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_height',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='activity',
            name='meals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='trip_duration',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='activity',
            name='trip_type',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
