# Generated by Django 5.1 on 2025-01-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0022_activity_accommodation_activity_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='accommodation',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='activity',
            name='meals',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
