# Generated by Django 5.1 on 2025-02-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0024_activitycheckout"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="slug",
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
