# Generated by Django 5.1 on 2025-02-07 17:45

from django.db import migrations, models
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    Destination = apps.get_model('activity', 'Destination')
    for destination in Destination.objects.all():
        if not destination.slug:  # Only update if slug is empty
            base_slug = slugify(destination.name)
            slug = base_slug
            counter = 1
            # Handle duplicate slugs by appending a number
            while Destination.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            destination.slug = slug
            destination.save()

def reverse_populate_slugs(apps, schema_editor):
    pass  # We don't want to reverse this operation

class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0025_destination_slug"),
    ]

    operations = [
        # First populate all empty slugs
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
        # Then make the field unique and non-nullable
        migrations.AlterField(
            model_name='destination',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
