# Generated by Django 5.1 on 2025-02-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0025_destination_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destination",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
