# Generated by Django 5.1 on 2025-03-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0026_fix_destination_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitybooking",
            name="group_price_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="activitybooking",
            name="group_size",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
