# Generated by Django 5.1 on 2025-02-07 17:38

from django.db import migrations
from django.utils.text import slugify

def populate_destination_slugs(apps, schema_editor):
    Destination = apps.get_model('activity', 'Destination')
    for destination in Destination.objects.all():
        base_slug = slugify(destination.name)
        slug = base_slug
        counter = 1
        # Handle duplicate slugs by appending a number
        while Destination.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        destination.slug = slug
        destination.save()

def reverse_destination_slugs(apps, schema_editor):
    Destination = apps.get_model('activity', 'Destination')
    Destination.objects.all().update(slug='')

class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0026_alter_destination_slug'),
    ]

    operations = [
        migrations.RunPython(populate_destination_slugs, reverse_destination_slugs),
    ]
