# Generated by Django 5.1 on 2025-04-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0027_activitybooking_group_price_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="slider",
            field=models.BooleanField(default=False),
        ),
    ]
